import { useMachine } from "@xstate/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useQuery } from "react-query";
import Container from "../components/Container";
import HeroPortrait from "../components/HeroPortrait";
import captainsModeMachine from "../state";

export interface Hero {
  id: number;
  img: string;
  localized_name: string;
}

const Home: NextPage = () => {
  const { data } = useQuery<{ [key: string]: Hero }>(["heroes"], async () => {
    return fetch("https://api.opendota.com/api/constants/heroes").then((data) =>
      data.json()
    );
  });

  const [state, send] = useMachine(captainsModeMachine);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <div className="flex">
            <div className="px-4">
              {data ? (
                <ul className="flex flex-wrap gap-4">
                  {Object.values(data)
                    .slice(0, 5)
                    .map((hero) => (
                      <li key={hero.id}>
                        <HeroPortrait
                          disabled={
                            state.matches("idle") ||
                            state.context.heroesBanned.includes(hero.id) ||
                            state.context.heroesPicked.includes(hero.id)
                          }
                          hero={hero}
                          isSelected={hero.id === state.context.selectedHeroId}
                          onClick={() => {
                            send({ type: "SELECT_HERO", heroId: hero.id });
                          }}
                        />
                      </li>
                    ))}
                </ul>
              ) : null}
            </div>
            <div className="px-4 space-y-4">
              <p>Turn: {state.context.turn}</p>
              <p>
                Hero:{" "}
                {data
                  ? Object.values(data).find(
                      (hero) => hero.id === state.context.selectedHeroId
                    )?.localized_name
                  : null}
              </p>
              {state.matches("idle") && (
                <button onClick={() => send("START_GAME")}>Start Game</button>
              )}
              {state.matches("game.banning") && (
                <button
                  onClick={() =>
                    state.context.selectedHeroId
                      ? send({
                          type: "BAN",
                          heroId: state.context.selectedHeroId,
                        })
                      : undefined
                  }
                >
                  Ban
                </button>
              )}
              {state.matches("game.picking") && (
                <button
                  onClick={() =>
                    state.context.selectedHeroId
                      ? send({
                          type: "PICK",
                          heroId: state.context.selectedHeroId,
                        })
                      : undefined
                  }
                >
                  Pick
                </button>
              )}
            </div>
          </div>
        </Container>
      </main>
    </>
  );
};

export default Home;
